# Generated by Django 4.2.5 on 2023-09-12 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="musician",
            name="instruments",
        ),
    ]
