# Generated by Django 4.2.5 on 2023-09-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_remove_musician_instruments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
