# Generated by Django 4.2.5 on 2023-10-22 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_band_options_alter_performance_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="instrument",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="musician",
            options={"ordering": ["full_name"], "verbose_name": "musician"},
        ),
    ]
